company:
  apiUrl: https://www.alphavantage.co/query?function=OVERVIEW&symbol=
  apiKey: LIAYMT70Q1XLIOZ8
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fairtrade
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update

  application:
    name: demo